name: "Test"
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test (${{ matrix.os }}) - (CLI ${{ matrix.cli-version || 'default' }})
    runs-on: ${{ matrix.os }}
    env:
      JF_ENV_LOCAL: ${{ secrets.JF_ENV_LOCAL }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-15 ]
        cli-version: [ "", "latest", "1.46.4" ]
      fail-fast: false
    steps:
      # Checkout and install prerequisites
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup NodeJS
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "20.x"

      # Run action according to the input version
      - name: Setup JFrog CLI
        if: matrix.cli-version != ''
        uses: ./
        with:
          version: ${{ matrix.cli-version }}
      - name: Setup default JFrog CLI
        if: matrix.cli-version == ''
        uses: ./

      # Run --version
      - name: Check versions
        run: jf --version && jfrog --version

      # Check local server successfully configured
      - name: Sanity
        run: jf c show local || jfrog rt config show local

      # Check build URL
      - name: Check build URL
        uses: wei/curl@012398a392d02480afa2720780031f8621d5f94c # master
        with:
          args: -I ${JFROG_CLI_BUILD_URL}
        if: runner.os == 'Linux'

      # Check environment variables
      - name: Check action environment
        run: node scripts/check-env.js

      # Install and run tests
      - name: Install
        run: npm i
      - name: Unit tests
        run: npm t
